// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9J5Ba_hDesTusIzs798qrrv6T9eGYbWc',
    appId: '1:949637696820:web:b6dc4434b12e7852436961',
    messagingSenderId: '949637696820',
    projectId: 'guardian-angel-e5ad0',
    authDomain: 'guardian-angel-e5ad0.firebaseapp.com',
    storageBucket: 'guardian-angel-e5ad0.firebasestorage.app',
    measurementId: 'G-RS3RVZHSMC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3vQg219902F3ZV6b8KRuQ0m9FUJ6uiyQ',
    appId: '1:949637696820:android:cf7eefbd933b6c48436961',
    messagingSenderId: '949637696820',
    projectId: 'guardian-angel-e5ad0',
    storageBucket: 'guardian-angel-e5ad0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA9-fAD_xzTV8PhzY7mV8o5OLBCYoDi_Q',
    appId: '1:949637696820:ios:0f5e2e338bf27ddd436961',
    messagingSenderId: '949637696820',
    projectId: 'guardian-angel-e5ad0',
    storageBucket: 'guardian-angel-e5ad0.firebasestorage.app',
    iosBundleId: 'com.guardianangel.guardianAngelFyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA9-fAD_xzTV8PhzY7mV8o5OLBCYoDi_Q',
    appId: '1:949637696820:ios:c2dba024d2f8ce58436961',
    messagingSenderId: '949637696820',
    projectId: 'guardian-angel-e5ad0',
    storageBucket: 'guardian-angel-e5ad0.firebasestorage.app',
    iosBundleId: 'com.example.guardianAngelFyp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9J5Ba_hDesTusIzs798qrrv6T9eGYbWc',
    appId: '1:949637696820:web:562b487641900827436961',
    messagingSenderId: '949637696820',
    projectId: 'guardian-angel-e5ad0',
    authDomain: 'guardian-angel-e5ad0.firebaseapp.com',
    storageBucket: 'guardian-angel-e5ad0.firebasestorage.app',
    measurementId: 'G-QF3ZBML46H',
  );
}
